# Server settings
server.port=8081

# Database Settings
spring.datasource.url=jdbc:mysql://localhost:3306/task_manager_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret and Expiration (1 day = 86400000 ms)
taskmanager.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
taskmanager.app.jwtExpirationMs=86400000
