# Server
server.port=${PORT:8081}

# Database
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${{3d3aeff6-cbd5-402d-a887-9fb4e4570159.MYSQLPASSWORD}}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
taskmanager.app.jwtSecret=${JWT_SECRET}
taskmanager.app.jwtExpirationMs=86400000