# Server
server.port=${PORT}

# Database (CORRECT)
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
taskmanager.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
taskmanager.app.jwtExpirationMs=86400000